Cita/urls.py
from django.conf.urls import url,include
from . import views
from django.contrib.auth.decorators import login_required
from .views import CrearCita,ListadoCita,EditarCita,EliminarCita,VerCita

""" ejemplo de url: categorias/registrar """

""" los pk en la url de editar y eliminar sirven para saber sobre que dato
se esta trabajando """
urlpatterns = [
    url(r'^crearcita$', login_required(CrearCita.as_view()), name='CrearCita'),
    url(r'^listadocita$', login_required(ListadoCita.as_view()), name='ListadoCita'),
    url(r'^editarcita/(?P<pk>\d+)$', login_required(EditarCita.as_view()), name='EditarCita'),
    url(r'^eliminarcita/(?P<pk>\d+)$', login_required(EliminarCita.as_view()), name='EliminarCita'),
    url(r'^vercita/(?P<pk>\d+)$', login_required(VerCita.as_view()), name='VerCita'),
]

Clinica/urls.py
from django.conf.urls import url,include
from . import views
from django.contrib.auth.decorators import login_required
from .views import CrearClinica,ListadoClinica,EditarClinica,EliminarClinica

""" ejemplo de url: categorias/registrar """

""" los pk en la url de editar y eliminar sirven para saber sobre que dato
se esta trabajando """
urlpatterns = [
    url(r'^crearclinica$', login_required(CrearClinica.as_view()), name='CrearClinica'),
    url(r'^listadoclinica$', login_required(ListadoClinica.as_view()), name='ListadoClinica'),
    url(r'^editarclinica/(?P<pk>\d+)$', login_required(EditarClinica.as_view()), name='EditarClinica'),
    url(r'^eliminarclinica/(?P<pk>\d+)$', login_required(EliminarClinica.as_view()), name='EliminarClinica'),
]

Contable/urls.py
from django.conf.urls import url,include
from . import views
from django.contrib.auth.decorators import login_required
# from .views import CrearMovimientoCita,ListadoMovimientoCita,EditarMovimientoCita,EliminarMovimientoCita
from .views import BaseContable,ObtenerMovimientos,ObtenerMovimientoEspecifico,CrearMovimientoCita,ObtenerMoneda


""" ejemplo de url: categorias/registrar """

""" los pk en la url de editar y eliminar sirven para saber sobre que dato
se esta trabajando """
urlpatterns = [
url(r'^basecontable$', login_required(BaseContable.as_view()), name='BaseContable'),
# retorna un json con los movimientos solicitados
url(r'^api-ObtenerMovimientos$', ObtenerMovimientos, name='api-ObtenerMovimientos'),
url(r'^api-ObtenerMovimientoEspecifico/(?P<pk>\d+)$', ObtenerMovimientoEspecifico, name='api-ObtenerMovimientoEspecifico'),
url(r'^api-ObtenerMoneda$', ObtenerMoneda, name='api-ObtenerMoneda'),


url(r'^crearmovimientocita/(?P<pk>\d+)$', login_required(CrearMovimientoCita.as_view()), name='CrearMovimientoCita'),
# url(r'^listadomovimientocita$', login_required(ListadoMovimientoCita.as_view()), name='ListadoMovimientoCita'),
# url(r'^editarmovimientocita/(?P<pk>\d+)$', login_required(EditarMovimientoCita.as_view()), name='EditarMovimientoCita'),
# url(r'^eliminarmovimientocita/(?P<pk>\d+)$', login_required(EliminarMovimientoCita.as_view()), name='EliminarMovimientoCita'),
]

Doctor/urls.py
from django.conf.urls import url,include
from . import views
from django.contrib.auth.decorators import login_required
from .views import CrearDoctor,ListadoDoctor,EditarDoctor,EliminarDoctor

""" ejemplo de url: categorias/registrar """

""" los pk en la url de editar y eliminar sirven para saber sobre que dato
se esta trabajando """
urlpatterns = [
    url(r'^creardoctor$', login_required(CrearDoctor.as_view()), name='CrearDoctor'),
    url(r'^listadodoctor$', login_required(ListadoDoctor.as_view()), name='ListadoDoctor'),
    url(r'^editardoctor/(?P<pk>\d+)$', login_required(EditarDoctor.as_view()), name='EditarDoctor'),
    url(r'^eliminardoctor/(?P<pk>\d+)$', login_required(EliminarDoctor.as_view()), name='EliminarDoctor'),
]

GECISoft/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from Usuarios.views import InicioView,EnvioCorreo
from django.contrib.auth.views import login,logout_then_login,logout
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls import include
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^enviocorreo/',EnvioCorreo.as_view(),name='EnvioCorreo' ),
    url(r'^login',login,{'template_name':'templates/login.html'},name='login'),
    url(r'^logout',logout,{'next_page':'login'},name='logout'),
    url(r'^auth/', include('social_django.urls', namespace='social')),
]

urlpatterns += i18n_patterns(
    url(r'^$', login_required(InicioView.as_view()),name='inicio'),
    url(r'^administrador/',include('Usuarios.urls', namespace='adminUrl') ),
    url(r'^clinica/',include('Clinica.urls', namespace='clinicaUrl') ),
    url(r'^paciente/',include('Paciente.urls', namespace='pacienteUrl') ),
    url(r'^cita/',include('Cita.urls', namespace='citaUrl') ),
    url(r'^doctor/',include('Doctor.urls', namespace='doctorUrl') ),
    url(r'^movimientocita/',include('Contable.urls', namespace='movimientocitaUrl') ),
)

Paciente/urls.py
from django.conf.urls import url,include
from . import views
from django.contrib.auth.decorators import login_required
from .views import CrearPaciente,ListadoPaciente,EditarPaciente,EliminarPaciente

""" ejemplo de url: categorias/registrar """

""" los pk en la url de editar y eliminar sirven para saber sobre que dato
se esta trabajando """
urlpatterns = [
    url(r'^crearpaciente$', login_required(CrearPaciente.as_view()), name='CrearPaciente'),
    url(r'^listadopaciente$', login_required(ListadoPaciente.as_view()), name='ListadoPaciente'),
    url(r'^editarpaciente/(?P<pk>\d+)$', login_required(EditarPaciente.as_view()), name='EditarPaciente'),
    url(r'^eliminarpaciente/(?P<pk>\d+)$', login_required(EliminarPaciente.as_view()), name='EliminarPaciente'),
]

site-templates/templates/index.html
{% load staticfiles %}
{% load i18n %}
<style>
    .left_col {
    background: {{user.clinica.color_menu}} !important;
}
body {
    background: {{user.clinica.color_footer}} !important;
}
.nav.side-menu>li>a, .nav.child_menu>li>a {
    color: {{user.clinica.color_texto_menu}} !important;
    
}
.menu_section h3 {
    color: {{user.clinica.color_texto_menu}} !important;
    
}
.profile_info h2 {
    color: {{user.clinica.color_texto_menu}} !important;
}
.profile_info span {
    color: {{user.clinica.color_texto_menu}} !important;
}
</style>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title id="titulo"></title>

    <!-- Bootstrap -->
    <link href='{% static "vendors/bootstrap/dist/css/bootstrap.min.css" %}' rel="stylesheet">
    <!-- Font Awesome -->
    <link href='{% static "vendors/font-awesome/css/font-awesome.min.css" %}' rel="stylesheet">

    <link href='{% static "vendors/bootstrap-daterangepicker/daterangepicker.css" %}' rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href='{% static "build/css/custom.css" %}' rel="stylesheet">
    <!-- Datatables -->
    <link href='{% static "vendors/datatables.net-bs/css/dataTables.bootstrap.min.css"%}' rel="stylesheet">
    <link href='{% static "vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css"%}' rel="stylesheet">
    <link href='{% static "vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css"%}' rel="stylesheet">
    <link href='{% static "vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css"%}' rel="stylesheet">
    <link href='{% static "vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css"%}' rel="stylesheet">
    <style>
        {% block style %} 
        {% endblock %}
    </style>


    <!-- DatePicker -->
    <link href='{% static "vendors/bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css"%}' rel="stylesheet">
    {% block head %}
     {% endblock %}

</head>

<body class="nav-md" >

    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">

                    </div>

                    <div style="padding-left:12%;">
                    <!-- <img src='{% static "imagenes/logo1.png" %}' width="85%"> -->
                    </div>


                    <div class="profile clearfix">

                      <div class="profile_info">
                          <h2>{{user.clinica.nombre}}</h2>
                          <span>{% trans "Bienvenido" %}</span>
                          <h2>{{user.nombre}}</h2>
                          <h2>{{user.username}}</h2>
                      </div>
                        {% block username %}
                         {% endblock %}
                    </div>


                    <br />

                    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                        {% if not user.is_admin %}
                        <div class="menu_section">
                            <h3>General</h3>
                            <ul class="nav side-menu">
                                <li><a href="{% url 'inicio' %}"><i class="fa fa-home"></i> {% trans "Inicio" %} <span ></span></a>
                                  <li><a><i class="fa fa-group"></i>{% trans "Pacientes" %}<span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                      <li><a href='{% url "pacienteUrl:ListadoPaciente" %}'>{% trans "Listado" %}</a></li>
                                      <li><a href='{% url "pacienteUrl:CrearPaciente" %}'>{% trans "Agregar" %}</a></li>
                                    </ul>
                                  </li>
                                  <li><a><i class="fa fa-user-md"></i> {% trans "Doctores" %} <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                      <li><a href='{% url "doctorUrl:ListadoDoctor" %}'> {% trans "Listado" %}</a></li>
                                      <li><a href='{% url "doctorUrl:CrearDoctor" %}'>{% trans "Agregar" %}</a></li>
                                    </ul>
                                  </li>
                                </li>
                                <li><a><i class="fa fa-calendar"></i> {% trans "Citas" %} <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href='{% url "citaUrl:ListadoCita" %}'>{% trans "Listado" %}</a></li>
                                        <li><a href='{% url "citaUrl:CrearCita" %}' >{% trans "Agregar" %}</a></li>

                                    </ul>
                                </li>
                                <li><a><i class="fa fa-money"></i> {% trans "Movimientos Contables" %} <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href='{% url "movimientocitaUrl:BaseContable" %}'>{% trans "Listado" %}</a></li>
                                    </ul>
                                </li>
                                <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out pull-right"></i> {% trans "Cerrar Sesion" %}</a></li>

                            </ul>
                        </div>
                        {% endif %}
                        {% if user.is_admin %}
                        <div class="menu_section">
                            <h3>{% trans "Sistema" %}</h3>
                            <ul class="nav side-menu">
                                <li><a><i class="fa fa-group"></i> {% trans "Usuarios" %} <span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="{% url 'adminUrl:ListadoUsuario' %}" >{% trans "Listado" %}</a></li>
                                        <li><a href="{% url 'adminUrl:CrearUsuario' %}">{% trans "Agregar" %}</a></li>


                                    </ul>
                                </li>
                                <li><a><i class="fa fa-building"></i>{% trans "Clinicas" %}<span class="fa fa-chevron-down"></span></a>
                                    <ul class="nav child_menu">
                                        <li><a href="{% url 'clinicaUrl:ListadoClinica' %}">{% trans "Listado" %}</a></li>
                                        <li><a href="{% url 'clinicaUrl:CrearClinica' %}">{% trans "Agregar" %}</a></li>
                                    </ul>
                                </li>
                                <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out pull-right"></i> {% trans "Cerrar Sesion" %}</a></li>


                            </ul>

                        </div>
                        {% endif %}


                    </div>

                    <!-- /sidebar menu -->

                    <!-- /menu footer buttons -->

                    <!-- /menu footer buttons -->
                </div>
            </div>

            <!-- top navigation -->
            <div class="top_nav">
                <div class="nav_menu">

                    <nav>
                        <div class="nav toggle">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>
                        <ul class="nav navbar-nav navbar-right">
                        </ul>
                    </nav>

                </div>
            </div>
            <!-- /top navigation -->

            <!-- page content -->
            <div class="right_col" role="main">
                <!-- top tiles -->
                <div class="row tile_count">
                    {% block bodyTop %}

                    {% endblock %}


                    {% block body %} {% endblock %}
                </div>
            </div>

        </div>
        <div style="padding-left:45%;">
          <!-- <img src='{% static "imagenes/logo.png" %}'  style="bottom:0;left:100px;margin-right:25px;"width="10%"> -->
        </div>

    </div>
    


    <!-- jQuery -->
    <script src='{% static "vendors/jquery/dist/jquery.min.js" %}'></script>
    <!-- Bootstrap -->
    <script src='{% static "vendors/bootstrap/dist/js/bootstrap.min.js" %}'></script>

    <script src='{% static "vendors/moment/min/moment.min.js" %}'></script>
    <!-- FastClick -->
    <script src='{% static "vendors/fastclick/lib/fastclick.js" %}'></script>
    <!-- NProgress -->
    <script src='{% static "vendors/nprogress/nprogress.js" %}'></script>
    <!-- bootstrap-progressbar -->
    <script src='{% static "vendors/bootstrap-progressbar/bootstrap-progressbar.min.js" %}'></script>
    <!-- iCheck -->
    <script src='{% static "vendors/iCheck/icheck.min.js" %}'></script>
    <!-- bootstrap-wysiwyg -->
    <script src='{% static "vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js" %}'></script>
    <script src='{% static "vendors/jquery.hotkeys/jquery.hotkeys.js" %}'></script>
    <script src='{% static "vendors/google-code-prettify/src/prettify.js" %}'></script>
    <!-- jQuery Tags Input -->
    <script src='{% static "vendors/jquery.tagsinput/src/jquery.tagsinput.js" %}'></script>
    <!-- Switchery -->
    <script src='{% static "vendors/switchery/dist/switchery.min.js" %}'></script>
    <!-- Select2 -->
    <script src='{% static "vendors/select2/dist/js/select2.full.min.js" %}'></script>
    <!-- Parsley -->
    <script src='{% static "vendors/parsleyjs/dist/parsley.min.js" %}'></script>
    <!-- Autosize -->
    <script src='{% static "vendors/autosize/dist/autosize.min.js" %}'></script>
    <!-- jQuery autocomplete -->
    <script src='{% static "vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js" %}'></script>
    <!-- starrr -->
    <script src='{% static "vendors/starrr/dist/starrr.js" %}'></script>

    <script src='{% static "vendors/datatables.net/js/jquery.dataTables.min.js" %}'></script>
    <script src='{% static "vendors/datatables.net-bs/js/dataTables.bootstrap.min.js" %}'></script>
    <script src='{% static "vendors/datatables.net-buttons/js/dataTables.buttons.min.js" %}'></script>
    <script src='{% static "vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js" %}'></script>
    <script src='{% static "vendors/datatables.net-buttons/js/buttons.flash.min.js" %}'></script>
    <script src='{% static "vendors/datatables.net-buttons/js/buttons.html5.min.js" %}'></script>
    <script src='{% static "vendors/datatables.net-buttons/js/buttons.print.min.js" %}'></script>
    <script src='{% static "vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js" %}'></script>
    <script src='{% static "vendors/datatables.net-keytable/js/dataTables.keyTable.min.js" %}'></script>
    <script src='{% static "vendors/datatables.net-responsive/js/dataTables.responsive.min.js" %}'></script>
    <script src='{% static "vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js" %}'></script>
    <script src='{% static "vendors/datatables.net-scroller/js/dataTables.scroller.min.js" %}'></script>

    <script src='{% static "build/js/custom.js" %}'></script>
    <script src='{% static "vendors/moment/locale/es.js"%}'></script>
    <script src='{% static "vendors/bootstrap-daterangepicker/daterangepicker.js" %}'></script>
    <script src='{% static "vendors/bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js" %}'></script>
    <script src='{% static "vendors/Chart.js/dist/Chart.min.js" %}'></script>
    <!-- Angular js -->
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js"></script>
    <script src='{% static "angularjs/main.js" %}'></script>

    {% block body_bottom %} {% endblock %}
</body>

</html>

site-templates/templates/inicio.html
{% extends 'Templates/index.html' %} {% load widget_tweaks %} 

{% block bodyTop %}
<div>


</div>

<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="fa fa-user"></i> Total de Pacientes</span>
    <div class="count green">{{ pacientes|length }}</div>

</div>
<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="fa fa-group"></i> Total de Doctores</span>
    <div class="count">
        {{ doctor|length }} </div>

</div>
<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="fa fa-graduation-cap"></i> Total de Usuarios</span>
    <div class="count green">{{usuarios|length}}</div>

</div>
<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="fa fa-money"></i> Total de Movimientos Contables</span>
    <div class="count"></div>

</div>
<div class="col-md-2 col-sm-4 col-xs-6 tile_stats_count">
    <span class="count_top"><i class="fa fa-calculator"></i> Total de Citas</span>
    <div class="count green"></div>

</div>

{% endblock %}
{% block body %}

<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
        <li class="{{ message.tags }}"><h2>{{ message }}</h2></li>
        </div>
      {% endfor %}
    </ul>
    {% endif %}

    {% if user.is_admin %}
      <div class="x_panel">
          <div class="x_title">
              <h2>Notificaciones Para Ti</h2>

              <div class="clearfix"></div>
          </div>
          <div class="x_content">
              <table id="datatables" class="table table-striped table-bordered" cellspacing="0" width="100%">
                  <thead>
                      <tr>
                          <th>id</th>
                          <th>Nombre</th>
                          <th>Correo</th>
                          <th>Tema</th>
                          <th>Mensaje</th>
                      </tr>
                  </thead>
                  <tbody>
                      {% for dato in solicitudes %} 
                      <tr>
                          <td>{{dato.id}}</td>
                          <td>{{dato.nombre_completo}}</td>
                          <td>{{dato.correo}}</td>
                          <td>{{dato.tema}}</td>
                          <td>{{dato.mensaje}}</td>
                      </tr>
                      {% endfor %}
                  </tbody>
              </table>


          </div>

      </div>
      {% endif %}

  </div>

</div>


{% endblock %}

site-templates/templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V3</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "login/vendor/bootstrap/css/bootstrap.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "login/fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "login/fonts/iconic/css/material-design-iconic-font.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "login/vendor/animate/animate.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "login/vendor/css-hamburgers/hamburgers.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "login/vendor/animsition/css/animsition.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "login/vendor/select2/select2.min.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "login/vendor/daterangepicker/daterangepicker.css" %}'>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href='{% static "login/css/util.css" %}'>
	<link rel="stylesheet" type="text/css" href='{% static "login/css/main.css" %}'>
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter">
			{% if message %}
			<div class="alert alert-danger alert-dismissible fade in" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
				</button>
				<strong><h4>{{message}}</h4></strong>
			</div>
		{% endif %}
		<div class="container-login100" style="background-image: url('static/login/images/bg-01.jpg');">
			<div class="wrap-login100">
				<form class="login100-form validate-form" method="POST">
					{% csrf_token %}
					<span class="login100-form-logo">
						<i class="zmdi zmdi-landscape"></i>
					</span>
					<span class="login100-form-title p-b-34 p-t-27">
						Inicio de Sesion
					</span>
						<div class="wrap-input100 validate-input" data-validate = "Ingresar Usuario">
							<input class="input100" id="username" type="text" name="username" placeholder="Usuario">
							<span class="focus-input100" data-placeholder="&#xf207;"></span>
						</div>

						<div class="wrap-input100 validate-input" data-validate="Ingresar Contraseña">
							<input class="input100" id="password" type="password" name="password" placeholder="Contraseña">
							<span class="focus-input100" data-placeholder="&#xf191;"></span>
						</div>
						<div class="container-login100-form-btn">
							<button class="login100-form-btn" type='submit' value="Iniciar Sesion">
								Iniciar Sesion
							</button>
						</div>
						<div  >
							<span class="login100-form-title p-b-34 p-t-27">
								Otras alternativas
							</span>
							<div class="row" >
								<div class="col-md-6">
									<a href="{% url 'social:begin' 'google-oauth2' %}" class="btn  btn-danger azm-social azm-btn azm-border-bottom azm-google"><i class="fa fa-google"></i> Log in with Google</a>
								</div>
								<div class="col-md-6">
										<a href="{% url 'social:begin' 'facebook' %}" class="btn  btn-primary azm-social azm-btn azm-border-bottom azm-facebook"><i class="fa fa-facebook"></i> Log in with Facebook</a>
								</div>
							</div>
							<div class="row" style="padding-left:25%" >
									<div class="col-md-12">
										<a href="/enviocorreo" class="btn  btn-success"><i class="fa fa-user"></i> Unirse a GECI Software</a>
									</div>
								</div>
							</div>
				</form>
			</div>
		</div>
	</div>

	
	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src='{% static "login/vendor/jquery/jquery-3.2.1.min.js" %}'></script>
<!--===============================================================================================-->
	<script src='{% static "login/vendor/animsition/js/animsition.min.js" %}'></script>
<!--===============================================================================================-->
	<script src='{% static "login/vendor/bootstrap/js/popper.js" %}'></script>
	<script src='{% static "login/vendor/bootstrap/js/bootstrap.min.js" %}'></script>
<!--===============================================================================================-->
	<script src='{% static "login/vendor/select2/select2.min.js" %}'></script>
<!--===============================================================================================-->
	<script src='{% static "login/vendor/daterangepicker/moment.min.js" %}'></script>
	<script src='{% static "login/vendor/daterangepicker/daterangepicker.js" %}'></script>
<!--===============================================================================================-->
	<script src='{% static "login/vendor/countdowntime/countdowntime.js" %}'></script>
<!--===============================================================================================-->
	<script src='{% static "login/js/main.js" %}'></script>
	

</body>
</html>